name: Build and Deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8.2]
        # python_version: [3.5.7, 3.6.10, 3.7.5, 3.8.2]

  steps:
  # Check out the repository in the runner
  - uses: actions/checkout@v2
  
  # Install Python 3.9
  - name: Install Python 3.8.2
  uses: actions/setup-python@v2
    with:
      python-version: 3.8.2
  
  # Install the EB CLI using pip
  - name: Install EB CLI
    run: |
      python -m pip install --upgrade pip
      pip install awsebcli
  
  # Deploy to EB
  - name: Deploy to Elastic Beanstalk
    run: |
      eb deploy
